### ISSUE TITLE
Formatos varios

### ISSUE THREAD

**Issue by damiancastelao** [damiancastelao/JugandoConIssues#3] opened 2023-03-24 08:17 UTC
Escribe un comentario a este issue utilizando todos los posibles formatos disponibles

**Comment by LidierRaccioppe** [comment] 2023-03-24 08:19
@LidierRaccioppe  #- [ ] 1. ### **_
- [ ] 2. 
- [ ] 3. > `[> Escribe un comentario a este issue utilizando todos los posibles formatos disponibles]`
- [ ] 4. 
- [ ] 5. _**
- [ ] 6. 
- [ ] 7.

**Comment by SilverClick** [comment] 2023-03-24 08:19
**holaaaaaaaaaa**       **bbbbbbbbbb**     ###   aaaa                          @JayBGB            #2

**Comment by PPAGabriel** [comment] 2023-03-24 08:20
### Hola **Nena** _Cómo tú te llama?

> Desayuna con huevo
`jugo de china del good_`
[pulpa](url)

- I love you

1. Dos
2. Tres

- [ ] Fernando Alonso
- [ x] Tú

@PedroSanchez

**Comment by Miguii-6** [comment] 2023-03-24 08:20
### hola
**hola**
_hola_

> en el mercho

`escuchando mercho`

- adios 

1. adios

- [ ] adios


@mundo

**Comment by WindaLobo** [comment] 2023-03-24 08:20
**_

- [ ] @1. > Permite obtener reportes en formato xls aplicando distintos filtros. Se integra con un esquema de Single Sign On o autenticación tradicional.

_**

**Comment by JorgeAmestoy** [comment] 2023-03-24 08:20
### Hola
**Hola**
_Hola_

> Hola
`Hola`

1. Hola

- [ ] Hola

**Comment by NicolasRodriguezSteuerberg** [comment] 2023-03-24 08:21
@damiancastelao tengo un 10?

- [ ] Si
- [ ] Si

**Comment by SilverClick** [comment] 2023-03-24 08:21
[https://chat.openai.com/chat](url)

**Comment by marcosfa00** [comment] 2023-03-24 08:21
String [] comentarios = new String[6];

Comentario 0
### Comentario 1
_Comentario2_

> comentario 3

> Comentario4
`for (int I = 0;i<6;i++){

comentarios[i] = comentario5
}`

[enlace](url) sin url

- comentario 6
- comentario 7

1. comentario 8
2. comentario 9
3. 

- [ ] comentario10
- [ ] comentario11
- [ ] commentary 12

@damiancastelao 
#1

**Comment by LidierRaccioppe** [comment] 2023-03-24 08:22
[aipwfh
ipafn paw
infa
pwinfpawinfpa
wifnawpifna
pwnfa
pwinfap
wnif](https://www.google.com/)
#2 
Duplicate of #/
awdaw

**Comment by cristianmoreiraa** [comment] 2023-03-24 08:23
![image](https://user-images.githubusercontent.com/113538958/227464327-344688a8-bd82-41b8-a63c-d6f260edea89.png)

**Comment by WindaLobo** [comment] 2023-03-24 08:23
![image](https://user-images.githubusercontent.com/113532585/227464394-6c45da65-b862-4e42-aad9-226bf58c4cc3.png)

**Comment by JayBGB** [comment] 2023-03-24 08:24
### Dios, **en ti** _confío_

> PUÑETA
`TE AMOOOOOOOOOOO_`
[Lagartija](url)

- Iguana, Lagarto

1. Con pulpa
2. Sin pulpa

- [x] 33?
- [ ] 32

@policia

**Comment by SilverClick** [comment] 2023-03-24 08:24
![image](https://user-images.githubusercontent.com/113641305/227464640-e6889ab7-ae08-40d1-99ba-ccd4cc7329c9.png)

**Comment by LidierRaccioppe** [comment] 2023-03-24 08:24
`select * from interpretesser;
`

**Comment by JayBGB** [comment] 2023-03-24 08:25
![pikacho](https://user-images.githubusercontent.com/113522984/227464828-87b194ca-1a51-42b5-8254-6fff14cb508d.jpg)

**Comment by RubenDanielCastelao** [comment] 2023-03-24 08:25
### Puñeetaaaaaaaaaaaaaaaa

**Numancia**

_Texto de lao_

> Giovanniiiiiiiiiiiiiiii

`String ejemploCodigo = new String`

[https://es.popnable.com/puerto-rico/cantantes/38977-jovani-vazquez/biografia-y-hechos](url)

- 1
- 2
- 3

@JayBGB 

![image](https://user-images.githubusercontent.com/113546809/227464871-fdfe1c48-bda3-4212-953f-133e14eba562.png)

**Comment by PPAGabriel** [comment] 2023-03-24 08:25
![pedro-sanchez-banador](https://user-images.githubusercontent.com/113558132/227464890-52e996c3-1dbe-4caf-ac70-3b35ae1af447.jpeg)

**Comment by JayBGB** [comment] 2023-03-24 08:26
![FCt3H06WYAEnDS0](https://user-images.githubusercontent.com/113522984/227465071-f6ce79db-0f13-4ff3-aa9b-dc417f51acc1.jpeg)

**Comment by JayBGB** [comment] 2023-03-24 08:27
![7aimbb](https://user-images.githubusercontent.com/113522984/227465419-5dd98b99-d38a-477f-8b8a-0b713b83618b.jpg)

**Comment by WindaLobo** [comment] 2023-03-24 08:28
#2

**Comment by JayBGB** [comment] 2023-03-24 08:28
![WhatsApp Image 2023-02-01 at 09 03 28](https://user-images.githubusercontent.com/113522984/227465637-3145efc8-f26e-4ec8-8603-00760229219b.jpeg)

**Comment by LidierRaccioppe** [comment] 2023-03-24 08:28
![El Lado de Japon mas cercano a japon](https://static.wikia.nocookie.net/b0ad3341-c547-43e7-b3b6-c140bba6c916/scale-to-width/755)

**Comment by WindaLobo** [comment] 2023-03-24 08:29
![image](https://user-images.githubusercontent.com/113532585/227465665-ac0ded34-8944-45ce-aedd-70b34807259d.png)
#2

**Comment by damiancastelao** [comment] 2023-03-24 08:30
[commit inicial](https://github.com/damiancastelao/JugandoConIssues/commit/fb4aee41cfdeda1a8f5809244e2f4b5ca743139e)

**Comment by SilverClick** [comment] 2023-03-24 08:30
https://user-images.githubusercontent.com/113641305/227466061-ca80632b-0b10-4a1c-be00-66a0d7181ada.mp4

**Comment by RubenDanielCastelao** [comment] 2023-03-24 08:31
[Commit de Nico](https://github.com/damiancastelao/JugandoConIssues/commit/fb4aee41cfdeda1a8f5809244e2f4b5ca743139e)

**Comment by cristianmoreiraa** [comment] 2023-03-24 08:31
https://user-images.githubusercontent.com/113538958/227466293-56efc3bf-bf2b-4382-8eb4-4a5cb32528a9.mp4

**Comment by JayBGB** [comment] 2023-03-24 08:34
[https://www.youtube.com/watch?v=oHg5SJYRHA0](ES MUY IMPORTANTE QUE VEÁIS ESTO, OS ENSEÑA A USAR CHATGPT PARA COPIAR SIN QUE SEA DETECTABLE, CORRED)

**Comment by RubenDanielCastelao** [comment] 2023-03-24 08:34
fb4aee41cfdeda1a8f5809244e2f4b5ca743139e

**Comment by NicolasRodriguezSteuerberg** [comment] 2023-03-24 08:35
fb4aee41cfdeda1a8f5809244e2f4b5ca743139e
El mejor commit, 10 de 10

**Comment by PPAGabriel** [comment] 2023-03-24 08:37
50048d49e19d691a9091dbee66f8c45867851ae4
Referencia a commit

**Comment by JayBGB** [comment] 2023-03-24 08:37
50048d49e19d691a9091dbee66f8c45867851ae4

**Comment by RubenDanielCastelao** [comment] 2023-03-24 08:38
NOOOOOOO @PPAGabriel  la manzanaaaaaaaaaa

**Comment by JayBGB** [comment] 2023-03-24 08:39
![image](https://user-images.githubusercontent.com/113522984/227468002-3e59dfe6-c280-40cf-bc73-99507a0f11ed.png)

**Closed** 2023-03-24 08:41 UTC
